trigger:
- main

pool:
  vmImage: ubuntu-latest

# several stages, each with its own jobs and steps
stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo FirstJob Build
  - job: SecondJob
    steps:
    - bash: echo SecondJob Build
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: FirstDeployment
    steps:
    - bash: echo FirstDeployment
- stage: QADeploy
  dependsOn: DevDeploy
  jobs:
  - job: FirstQA
    steps:
    - bash: echo FirstQA
- stage: ProdDeploy
  dependsOn:
  - Devdeploy
  - QADeploy
  jobs:
  - job: ProdDeployment
    steps:
    - bash: echo Production Deployment